### ISSUE TITLE
Selections disappear on target objects

### ISSUE THREAD

**Issue by undsoul** [rvspt/QuickAdhoc-QS#4]
_On a published .qvf app at qliksense , we noticed interesting behaviour of extension ;

After we select one or more dim and measure and then when we wait approximately 5 or more sec. selections disappear on target objects . Object turns back to first stat of it .

It only happens on published app. not on my work place._

Br,

**Comment by rvspt** [comment]
That is correct. I believe (and this is an assumption, please bear with me) it happens because something published should not be altered as it is the base for everybody. Might be some kind of defense mechanism from Sense server itself.

If you duplicate the sheet within the published app it behaves normally, without disappearing the "selections/configurations" you are making to the object using the extension.

If I find something out, I'll share it here.

**Comment by jhofsteenge** [comment]
I found a work-around for this issue for Qlik Sense Server.
If you change the autosave time (Engine -> Central -> Apps) too a large interval the problem is gone.
Hope this helps.

**Comment by qlikviewsense** [comment]
I don't know how to say "thank you" ! It works!! Yes, autosave was the guilty one!! Thank you!

**Comment by ferchops1987** [comment]
Thank you very much Jhof!!! I was getting crazy :P

**Comment by ferchops1987** [comment]
Thank you very much Jhof!!! I was getting crazy :P
